### ISSUE TITLE
CommandBarActions -> IsButtonAvailable Object NullReferenceExceptions

### ISSUE THREAD

**Issue by VanHinthem** [DynamicHands/Crm.Specflow#114]
I think line 50 in CommandBarActions.cs: 

var items = ribbon.FindElements(By.TagName("li"));

needs to be changed to: 

var items = ribbon.FindElements(By.TagName("button"));

**Comment by thathi** [comment]
@VanHinthem Looks the workaround has been fixed in this commit by @mVermaat  https://github.com/DynamicHands/Crm.Specflow/commit/4c07140236ee0e8400a1052b8f02adc32f51b012
