### ISSUE TITLE
Unable to set time value for datetime control

### ISSUE THREAD

**Issue by thathi** [DynamicHands/Crm.Specflow#117]
Unable to set time value some times. 

![image](https://user-images.githubusercontent.com/15817637/114917757-362c1c00-9e1e-11eb-9669-3631095e9d60.png)

Hoping after setting the date field if we clear the focus maight help.

**Comment by mVermaat** [comment]
@thathi You state this happens sometimes. Can you elaborate it a little bit when it happens?

**Comment by thathi** [comment]
@mVermaat I think its timing issue around finding the timeField element. For me its always failing. If I wait in debug mode for few seconds it is working as expected. Either we can do clearfocus after setting date field or waitfewseconds before finding time element would do. Hope this make sense. 


// Try Set Time
                var timeFieldXPath = By.XPath($"//div[contains(@data-id,'{field}.fieldControl._timecontrol-datetime-container')]/div/div/input");
                bool success = driver.TryFindElement(timeFieldXPath, out var timeField);

**Comment by mVermaat** [comment]
Makes sense, I'll run some tests soon to see how it works and ill accept the pull request if I don't see any issues.
