### ISSUE TITLE
Unable to find the ribbon

### ISSUE THREAD

**Issue by Hso-Paw** [DynamicHands/Crm.Specflow#64]
When running Specflow locally and activating a default Quote, for whatever reason the ribbon happened to pop in a few milliseconds too late. 

This made the test fail with the message "Unable to find the ribbon" (method **IsButtonAvailable()** in _CommandBarActions.cs_). Some form of delay/ rechecking would be helpful in such cases.

**Comment by mVermaat** [comment]
Actually the code is in EasyRepro not this framework. Will make a pull request for this

**Comment by mVermaat** [comment]
Did fix the IsButtonAvailable though too

**Comment by mVermaat** [comment]
Can be implemented when https://github.com/microsoft/EasyRepro/pull/807 is fixed
