### ISSUE TITLE
Async Process Wait Step does not wait for Flows

### ISSUE THREAD

**Issue by mike9182** [DynamicHands/Crm.Specflow#82]
The step "all asynchronous processes for {alias} are finished" does not wait for running Flows to finish.

I wasn't able to find a straightforward way to implement this so I created a question in the Power Automate community. 

https://powerusers.microsoft.com/t5/General-Power-Automate/Check-for-running-flows/m-p/531226#M48990

**Comment by mVermaat** [comment]
If anyone finds a good way to implement this, let me know. It would be a really good addition, but I don't how this can be done.

**Comment by MartijnJong** [comment]
@mVermaat  not sure if is a good way to implement this feature, but a potential workaround could be 'wait for [xxx] seconds' to continu the test. 

Since we rely on flow for many scenario's this would help in making the test cases. 

Is that feasible?
